name: app_gerenciador_filmes
description: Aplicativo Flutter para gerenciar um catálogo de filmes.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path_provider: ^2.1.1

  flutter_rating_bar: ^4.0.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
